Update build-linux.yml

diff --git a/.github/workflows/build-linux.yml b/.github/workflows/build-linux.yml
--- a/.github/workflows/build-linux.yml
+++ b/.github/workflows/build-linux.yml
@@ -114,16 +114,25 @@ jobs:
           git fetch --all --tags --force
           git submodule sync --recursive
           git submodule update --init --recursive
+      
           echo "Latest commit ----->>>>> $(git rev-parse HEAD)"
           echo "LAST_COMMITID=$(git rev-parse HEAD)" >> $GITHUB_ENV
+      
+          # Lấy tag mới nhất theo thời gian tag (nếu có)
+          LATEST_TAG=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | head -n 1 || echo "")
           
-          # Get the latest tag based on the time it was tagged (taggerdate)
-          LATEST_TAG=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | head -n 1)
+          if [ -z "$LATEST_TAG" ]; then
+            echo "Could not find any tag set to 0.0.0"
+            LATEST_TAG="0.0.0"
+            TAGGED_COMMIT="0000000"
+          else
+            TAGGED_COMMIT=$(git rev-list -n 1 "$LATEST_TAG")
+          fi
           CURRENT_COMMIT=$(git rev-parse HEAD)
-          TAGGED_COMMIT=$(git rev-list -n 1 $LATEST_TAG)
           echo "Latest tag found: $LATEST_TAG (commit $TAGGED_COMMIT)"
           echo "Current commit: $CURRENT_COMMIT"
           echo "LATEST_VERSION=$LATEST_TAG" >> $GITHUB_ENV
+
 
       - name: Generate build info
         working-directory: ${{ github.workspace }}
